name: Docker Image CI

on:
  - push

env:
  IMG: bxwill/qsphere
  ALI_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  TAG_PREFIX: ui
  CODE_ROOT: ui

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for branch
      run: |
        git_ref_type=$(echo "${{ github.ref }}" | awk -F '/' '{print $2}')
        git_ref_name=$(echo "${{ github.ref }}" | awk -F '/' '{print $NF}')
        if [[ "${git_ref_type}" == "heads" ]]; then
            echo -e "\nTriggered by branch ${git_ref_name}\n"
            if [[ "${git_ref_name}" == "master" ]]; then
                echo -e "Skip build since master branch"
            elif [[ "${git_ref_name}" == "develop" ]]; then
                echo -e "\nBuild ${TAG_PREFIX}-develop image\n"
                cd ./${CODE_ROOT}
                docker build . --file Dockerfile --tag ${IMG}:${TAG_PREFIX}-develop
                cd ..
                docker tag ${IMG}:${TAG_PREFIX}-develop ${ALI_REGISTRY}/${IMG}:${TAG_PREFIX}-develop
                echo -e "\nPush image into Hub Docker\n"
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
                docker push ${IMG}:${TAG_PREFIX}-develop
                echo -e "\nPush image into Ali registry\n"
                echo "${{ secrets.ALI_DC_PASSWORD }}" | docker login -u ${{ secrets.ALI_DC_USER }} --password-stdin ${ALI_REGISTRY}
                docker push ${ALI_REGISTRY}/${IMG}:${TAG_PREFIX}-develop
            fi
        else
            echo -e "\nSkip this step\n"
        fi
    - name: Build the Docker image for tag
      run: |
        git_ref_type=$(echo "${{ github.ref }}" | awk -F '/' '{print $2}')
        git_ref_name=$(echo "${{ github.ref }}" | awk -F '/' '{print $NF}')
        if [[ "${git_ref_type}" == "tags" ]]; then
            echo -e "\nTriggered by tag ${git_ref_name}"
            echo -e "Build ${TAG_PREFIX}-${git_ref_name} image\n"
            tag_0=${git_ref_name}
            tag_1=$(echo ${git_ref_name} | awk -F '.' '{print $1}')
            tag_2=$(echo ${git_ref_name} | awk -F '.' '{print $1"."$2}')
            tag_3="latest"
            cd ./${CODE_ROOT}
            docker build . --file Dockerfile --tag ${IMG}:${TAG_PREFIX}-${tag_0}
            cd ..
            docker tag ${IMG}:${TAG_PREFIX}-${tag_0} ${ALI_REGISTRY}/${IMG}:${TAG_PREFIX}-${tag_0}
            for retag in "${tag_1}" "${tag_2}" "${tag_3}"
            do
                docker tag ${IMG}:${TAG_PREFIX}-${tag_0} ${IMG}:${TAG_PREFIX}-${retag}
                docker tag ${IMG}:${TAG_PREFIX}-${tag_0} ${ALI_REGISTRY}/${IMG}:${TAG_PREFIX}-${retag}
            done
            echo -e "\nPush image into Hub Docker\n"
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
            for _tag in "${tag_0}" "${tag_1}" "${tag_2}" "${tag_3}"
            do
                docker push ${IMG}:${TAG_PREFIX}-${_tag}
            done
            echo -e "\nPush image into Ali registry\n"
            echo "${{ secrets.ALI_DC_PASSWORD }}" | docker login -u ${{ secrets.ALI_DC_USER }} --password-stdin ${ALI_REGISTRY}
            for _tag in "${tag_0}" "${tag_1}" "${tag_2}" "${tag_3}"
            do
                docker push ${ALI_REGISTRY}/${IMG}:${TAG_PREFIX}-${_tag}
            done
        else
            echo -e "\nSkip this step\n"
        fi
