name: Docker Image CI

on:
  - push

env:
  IMG: bxwill/qsphere
  ALI_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  TAG_PREFIX: ui
  CODE_ROOT: ui

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo -e "\nCheck branchs/tags\n"
        git_ref_type=$(echo "${{ github.ref }}" | awk -F '/' '{print $2}')
        git_ref_name=$(echo "${{ github.ref }}" | awk -F '/' '{print $NF}')

        if [[ "${git_ref_type}" == "heads" ]]; then
            echo -e "\nTriggered by branch ${git_ref_name}\n"
            if [[ "${git_ref_name}" == "master" ]]; then
                echo -e "Skip build since master branch"
                exit 0
            elif [[ "${git_ref_name}" == "develop" ]]; then

                echo -e "\nBuild and push ${TAG_PREFIX}-develop image\n"
                cd ./${CODE_ROOT}
                docker build . --file Dockerfile --tag ${IMG}:${TAG_PREFIX}-develop
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
                docker push ${IMG}:${TAG_PREFIX}-develop

                echo -e "\nPush image into Ali registry\n"
                echo "${{ secrets.ALI_DC_PASSWORD }}" | docker login -u ${{ secrets.ALI_DC_USER }} --password-stdin ${ALI_REGISTRY}
                docker tag ${IMG}:${TAG_PREFIX}-develop ${ALI_REGISTRY}/${IMG}:${TAG_PREFIX}-develop
                docker push ${ALI_REGISTRY}/${IMG}:${TAG_PREFIX}-develop
            fi

        elif [[ "${git_ref_type}" == "tags" ]]; then
            echo -e "\nTriggered by tag ${git_ref_name}"
            echo -e "Build and push ${TAG_PREFIX}-${git_ref_name} image\n"
            cd ./${CODE_ROOT}
            docker build . --file Dockerfile --tag ${IMG}:${TAG_PREFIX}-${git_ref_name}
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
            echo "${{ secrets.ALI_DC_PASSWORD }}" | docker login -u ${{ secrets.ALI_DC_USER }} --password-stdin ${ALI_REGISTRY}
            docker push ${IMG}:${TAG_PREFIX}-${git_ref_name}
            retag_1=$(echo ${git_ref_name} | awk -F '.' '{print $1}')
            retag_2=$(echo ${git_ref_name} | awk -F '.' '{print $1"."$2}')
            retag_3="latest"
            for retag in "${retag_1}" "${retag_2}" "${retag_3}"
            do
                [[ -z "${retag}" ]] && continue
                echo -e "\nRetag ${TAG_PREFIX}-${git_ref_name} to ${TAG_PREFIX}-${retag} and push it\n"
                docker tag ${IMG}:${TAG_PREFIX}-${git_ref_name} ${IMG}:${TAG_PREFIX}-${retag}
                docker push ${IMG}:${TAG_PREFIX}-${retag}
                echo -e "\nPush image into Ali registry\n"
                docker tag ${IMG}:${TAG_PREFIX}-${retag} ${ALI_REGISTRY}/${IMG}:${TAG_PREFIX}-${retag}
                docker push ${ALI_REGISTRY}/${IMG}:${TAG_PREFIX}-${retag}
            done
        fi
